[package]
name = "advent"
version = "0.1.0"
edition = "2021"
autobins = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
aho-corasick = "1.1.2"
anyhow = "1.0.75"
rayon = "1.8.0"
